# =============================================================================
# scripts\run_pytest_detached.ps1   (v1.7.39 workflow fix)
#
# Runs pytest fully detached from its caller so long baselines (>3 min) don't
# wedge MCP servers via held stdio pipes. Output streams to a log file; a
# sentinel file ('<log>.done') with the exit code is written when complete.
# Callers (humans, scripts, or MCP-driven sessions) poll the sentinel.
#
# Why this exists
# ---------------
# The Windows-MCP PowerShell tool has a ~4 min internal ceiling. When pytest
# runs longer than that as a direct child of an MCP PowerShell call, the
# parent shell never returns and MCP's stdio state never resets, wedging all
# subsequent tool calls until Claude Desktop restarts. Detaching the work
# and using a file-based completion signal avoids the held-pipe problem
# entirely.
#
# Why a wrapper file (not inline)
# --------------------------------
# Start-Process inline arg-passing struggles with quoting nested commands and
# redirection. A small generated wrapper .ps1 sidesteps that and is easier to
# diagnose if something goes wrong (the worker file itself is human-readable).
#
# Usage
# -----
#   powershell -NoProfile -File scripts\run_pytest_detached.ps1 `
#       -LogPath C:\tmp\pytest.log `
#       -PytestArgs 'tests/','-q','--tb=line'
#
# On completion, two files exist:
#   <LogPath>            -- full pytest stdout/stderr
#   <LogPath>.done       -- single line: 'EXIT:<code>'   (e.g. 'EXIT:0')
#
# Polling pattern
# ---------------
#   while (-not (Test-Path "$LogPath.done")) {
#       Start-Sleep -Seconds 15
#       # short MCP call: just read log tail to show progress
#   }
#   $result = Get-Content "$LogPath.done"    # 'EXIT:0' if green
# =============================================================================

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $LogPath,
    [Parameter(Mandatory)] [string[]] $PytestArgs,
    [string] $RepoRoot = "C:\Users\jmlee\Desktop\AL\Curator"
)

$ErrorActionPreference = 'Stop'

# Remove any prior sentinel so a stale 'done' doesn't fool the poller
$donePath = "$LogPath.done"
if (Test-Path $donePath) { Remove-Item $donePath -Force }
if (Test-Path $LogPath)  { Remove-Item $LogPath  -Force }

# Build the worker script that the detached PowerShell will run.
# Single-quoted here-string keeps $LASTEXITCODE etc. unexpanded;
# we splice in the runtime values explicitly.
$pytestArgsQuoted = ($PytestArgs | ForEach-Object { "'$_'" }) -join ', '

$worker = @"
# Auto-generated by run_pytest_detached.ps1 -- do not edit manually
`$env:QT_QPA_PLATFORM = 'offscreen'
`$env:PYTHONIOENCODING = 'utf-8'
Set-Location -Path '$RepoRoot'
`$pyExe  = Join-Path '$RepoRoot' '.venv\Scripts\python.exe'
`$args   = @($pytestArgsQuoted)
& `$pyExe -m pytest @args *> '$LogPath'
`$code = `$LASTEXITCODE
"EXIT:`$code" | Out-File -Encoding ascii -FilePath '$donePath'
"@

$workerPath = [System.IO.Path]::ChangeExtension($LogPath, ".worker.ps1")
$worker | Out-File -Encoding utf8 -FilePath $workerPath

# Spawn the worker via Start-Process WITHOUT -Wait and WITHOUT
# -RedirectStandardOutput. The spawned PowerShell handles its own
# I/O redirection internally (via the `*>` in the worker script), so
# no file handles cross the process boundary from caller -> worker.
# This is the critical bit that keeps MCP's stdio pipe free.
$proc = Start-Process `
    -FilePath 'powershell' `
    -ArgumentList '-NoProfile', '-NonInteractive', '-File', $workerPath `
    -WindowStyle Hidden `
    -PassThru

Write-Host "Spawned detached pytest:"
Write-Host "  PID:         $($proc.Id)"
Write-Host "  Log:         $LogPath"
Write-Host "  Sentinel:    $donePath"
Write-Host "  Worker:      $workerPath"
Write-Host ""
Write-Host "Poll '$donePath' for completion. Caller returns immediately."
